# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Zen and the Art of Software'
tagline:          '@hliyan'
description:      'Personal blog of H. N. Liyanage'
url:              http://hliyan.github.io
#baseurl:          '/'

author:
  name:           '@hliyan'
  url:            https://twitter.com/h_liyan
  image:         https://avatars1.githubusercontent.com/u/6211831

gems: [jekyll-paginate]
paginate:         10

# for feed.xml
name: 'Zen and the Art of Software'
description: 'Personal blog of H. N. Liyanage'
url: http://hliyan.github.io


