# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Zen and the Art of Software Development'
tagline:          '@hliyan'
description:      'Personal blog of H. N. Liyanage'
url:              http://hliyan.github.io
baseurl:          /

author:
  name:           '@hliyan'
  url:            https://twitter.com/h_liyan

paginate:         10

# for feed.xml
name: 'Zen and the Art of Software Development'
description: 'Personal blog of H. N. Liyanage'
url: http://hliyan.github.io

