# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'hliyan'
tagline:          'Zen and the Art of Software Development'
description:      'Personal blog of H. N. Liyanage'
url:              http://hliyan.github.io
baseurl:          /

author:
  name:           'H. N. Liyanage'
  url:            https://twitter.com/h_liyan

paginate:         10

