# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Zen and the Art of Software Development'
tagline:          '@hliyan'
description:      'Personal blog of H. N. Liyanage'
url:              http://hliyan.github.io
baseurl:          /

author:
  name:           '@hliyan'
  url:            https://twitter.com/h_liyan

paginate:         10

